### ISSUE TITLE
.on binding - took a look at your code

### ISSUE THREAD

**Issue by conoremclaughlin** [bennadel/AngularJS-Directive-Controllers#1]
Hi Ben,

I took a look at your code from your blog post, good stuff.  I was just curious about your use of element.on in the directives - does this come from jquery?  Or is this part of the angular syntax?  all the docs have been telling me to use .bind, which doesn't allow selectors from what i can tell.  only the event name.  have you discovered anything there? i'd like to do at least some event aggregration rather than throw ngClicks everywhere.

Thanks so much for any insight!

**Comment by bennadel** [comment]
@conoremclaughlin Hey man, so sorry for not getting back to you sooner. For some reason, I was not getting any GitHub notifications via email, and I just decided to see what that "blue dot" at the top of the page is (turns out, unread notifications).

I don't have a great answer for you. If you inlclue jQuery _before_ you include AngularJS, Angular will use jQuery to wrap the element references. Since I always do this, my "element" objects are jQuery references, _not_ the jQLite that ships with AngularJS. 

The reason I really like using .on() is that I can, 1) do event delegation, when I need to. And, 2), I can name-space my events:

element.on( "click.myDirectiveName" ). 

... this way, in the $destroy events I can easily unbind using just the name:

element.off( "click.myDirectiveName" ).

Most of the time, it's not really necessary; but, when it comes to things like binding events to Window / Document, you have to be really careful to no re-bind things unnecessarily AND not to unbind event handlers that aren't controlled by your directive.
